# MD5 盐值
password:
  salt: carlislesdafaqj23ou89ZXcj@#$@#$#@KJdjklj;D../dSF.,
# FTP 相关配置
ftp:
  server:
    ip: 114.55.173.45
    http:
      prefix: http://img.happymmall.com/
  user: mmallftp
  pass: ftppassword
# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://114.55.173.45:3306/mmall?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 60000
mybatis:
  type-aliases-package: com.carlisle.brown.mall.dao